export default chatList = [
    {
      id: 1,
      image: "",
      name: "John Doe",
      message: "Hello",
      time: "10:00 AM",
      status: "online",
      numberOfMsg: 2,
      isPinned: true,
    },
    {
      id: 2,
      image: "",
      name: "Jane Doe",
      message: "Hello",
      time: "10:00 AM",
      status: "online",
      numberOfMsg: 2,
      isPinned: true,
    },
    {
      id: 3,
      image: "",
      name: "Jane Doe",
      message: "Hello",
      time: "10:00 AM",
      status: "online",
      numberOfMsg: 2,
      isPinned: false,
    },
    {
      id: 4,
      image: "",
      name: "Jane Doe",
      message: "Hello",
      time: "10:00 AM",
      status: "online",
      numberOfMsg: 2,
      isPinned: false,
    },
    {
      id: 5,
      image: "",
      name: "Jane Doe",
      message: "Hello",
      time: "10:00 AM",
      status: "online",
      numberOfMsg: 2,
      isPinned: false,
    },
  ];