export default chatList = [
    {
      id: 1,
      image: "",
      name: "Emily",
      message: "Hello",
      time: "10:00 AM",
      status: "online",
      numberOfMsg: 2,
      isPinned: true,
    },
    {
      id: 2,
      image: "",
      name: "Anna",
      message: "Hello",
      time: "10:00 AM",
      status: "online",
      numberOfMsg: 1,
      isPinned: true,
    },
    {
      id: 3,
      image: "",
      name: "Farhan",
      message: "Hello",
      time: "10:00 AM",
      status: "offline",
      numberOfMsg: 0,
      isPinned: false,
    },
    {
      id: 4,
      image: "",
      name: "Amir",
      message: "Hello",
      time: "10:00 AM",
      status: "online",
      numberOfMsg: 0,
      isPinned: false,
    },
    {
      id: 5,
      image: "",
      name: "Jane Doe",
      message: "Hello",
      time: "10:00 AM",
      status: "offline",
      numberOfMsg: 0,
      isPinned: false,
    },
  ];